### ISSUE TITLE
Downgrade FLS version to 16429

### ISSUE THREAD

**Issue by burkov** [crazy-max/docker-jetbrains-license-server#1]
Build #16743 is an alpha version and was accidentally published yesterday to JB FTP server.

Could you please rollback your image to build #16429

**Comment by crazy-max** [comment]
Done, thanks for your input!

**Comment by crazy-max** [comment]
@burkov I've got a question about the delivery of FLS. Do you have a link including the release version?
Today we only have this link : https://download.jetbrains.com/lcsrv/license-server-installer.zip

Can you provide versioning links like these for example ? :
* https://download.jetbrains.com/lcsrv/16429/license-server-installer.zip
* https://download.jetbrains.com/lcsrv/license-server-installer-16429.zip

And also, do you have a changelog link?
