### ISSUE TITLE
you are using an outdated version of the license server

### ISSUE THREAD

**Issue by snowdream** [crazy-max/docker-jetbrains-license-server#14]
you are using an outdated version of the license server

**Comment by casz** [comment]
feel free to send a PR with the updated version? this is open source on GitHub after all :smile:

**Comment by casz** [comment]
@snowdream I don't think so tbh: 
![image](https://user-images.githubusercontent.com/1661688/53934538-90851b00-40a3-11e9-8bbb-04ab6cc0b594.png)

**Comment by crazy-max** [comment]
18692 is the latest version
