### ISSUE TITLE
License Server response has not passed data integrity check: Server is not registered

### ISSUE THREAD

**Issue by ghjacky** [crazy-max/docker-jetbrains-license-server#17]
I used `docker run` command in README file to start the license server. But I got error `Server is not registered` as the issue title. 
Why this happened ?
And how to resolve it ?
Thank you forward !

**Comment by crazy-max** [comment]
Please create a proper bug report : https://github.com/crazy-max/docker-jetbrains-license-server/blob/master/.github/SUPPORT.md
