### ISSUE TITLE
error message "No response"

### ISSUE THREAD

**Issue by jiayaoO3O** [crazy-max/docker-jetbrains-license-server#18]
**idea 2019.2**
I run commands  `docker run -d -p 8000:8000 --name jetbrains_license_server -e TZ="Asia/Shanghai" -e JLS_VIRTUAL_HOSTS=jetbrains-license-server.example.com -v $(pwd)/data:/data crazymax/jetbrains-license-server:latest`
on my host.When I try to activate the idea, I get the following message
![image](https://user-images.githubusercontent.com/22891632/62145113-7a634a00-b325-11e9-9612-33f3ee70861f.png)

**Comment by crazy-max** [comment]
Replace `JLS_VIRTUAL_HOSTS` value with your server IP/fqdn

**Comment by webcoderkz** [comment]
Can i set `JLS_VIRTUAL_HOSTS` as `127.0.0.1`?
