### ISSUE TITLE
Add proxy.hosts as env variables (due to being in enterprise/air gap)

### ISSUE THREAD

**Issue by dmpe** [crazy-max/docker-jetbrains-license-server#21]
Hi @crazy-max, 
great image. 
What I am missing however is the ability to pass proxy settings. Indeed, we want to use your image but are currently limited due to lacking the ability to pass proxy variables `https.proxyHost` and port

https://www.jetbrains.com/help/license_server/configuring_proxy_settings.html

Could you please adjust docker image ? Would be lovely. 
Thanks.

**Comment by crazy-max** [comment]
Hey @dmpe, looks ok for me. Keep you in touch and thanks for your support!

**Comment by crazy-max** [comment]
@dmpe Should be good, pull the latest image. See [env vars in README](https://github.com/crazy-max/docker-jetbrains-license-server#environment-variables) for more info and happy JLS :)

**Comment by casz** [comment]
Kudos @crazy-max 🙇
