### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by zhuqiming** [crazy-max/docker-jetbrains-license-server#22]
您好，最近刚刚了解docker，不太会使用您这个镜像，请教一下如何使用它

**Comment by crazy-max** [comment]
In english please

**Comment by zhuqiming** [comment]
sorry， Im a new in docker , i want to know how to use it , i read the README.md  and run a container in my mac ,visite http://127.0.0.1:8000 it income a page eg:
![Uploading ima
![企业微信截图_b13661cc-2212-4865-8dcb-b34ff2d1a222](https://user-images.githubusercontent.com/22165493/72250730-419b0100-3637-11ea-9636-c4157d9573b0.png)
ge.png…]()

it mean wo will use http://127.0.0.1:8000 this address to active goland?
