### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by zhuqiming** [crazy-max/docker-jetbrains-license-server#23]
sorry， Im a new in docker , i want to know how to use it , i read the README.md and run a container in my mac ,visite http://127.0.0.1:8000 it income a page eg:

![企业微信截图_b13661cc-2212-4865-8dcb-b34ff2d1a222](https://user-images.githubusercontent.com/22165493/72250963-cdad2880-3637-11ea-982b-8d01bd8d84bd.png)

it mean wo will use http://127.0.0.1:8000 this address to active goland?

**Comment by Winster332** [comment]
+

**Comment by crazy-max** [comment]
You need to register your server against your JetBrains account.
Moreinfo: https://www.jetbrains.com/help/license_server/register_server.html

**Comment by Winster332** [comment]
> You need to register your server against your JetBrains account.
> More info: https://www.jetbrains.com/help/license_server/register_server.html

After clicking the registration button, it shows this:

> You need admin access to your organization profile for license server registration.

What is the reason?

**Comment by casz** [comment]
@Winster332 I suggest contacting JetBrains license support, they are really friendly in helping with setup: https://www.jetbrains.com/license-server/contact-support/

This repo provides a docker image that helps host the JetBrains License server.

**Comment by Winster332** [comment]
> @Winster332 I suggest contacting JetBrains license support, they are really friendly in helping with setup: https://www.jetbrains.com/license-server/contact-support/
> 
> This repo provides a docker image that helps host the JetBrains License server.

Ok. Thanks
