### ISSUE TITLE
cannot get ACME client ACME challenge not specified, please select HTTP or DNS Challenge

### ISSUE THREAD

**Issue by waj6144** [crazy-max/docker-jetbrains-license-server#3]
I've got problems to get traefik to generate it's certificates.

Error was: `level=error msg="Unable to obtain ACME certificate for domains \"example.com\" detected thanks to rule \"Host:example.com\" : cannot get ACME client ACME challenge not specified, please select HTTP or DNS Challenge"`

The solution was to add the following traefik command in docker-compose.yml (in the _command:_ section):

`- --acme.httpChallenge.entryPoint=http`

Maybe this hint will help someone to save some time.

**Comment by crazy-max** [comment]
You right, thx for your input ;)

**Comment by crazy-max** [comment]
docker-compose file have been updated
