### ISSUE TITLE
HTTP ERROR 403

### ISSUE THREAD

**Issue by kazhian** [crazy-max/docker-jetbrains-license-server#4]
I hosted the docker image in out private cloud successfully. Service is up and running. But when I open the URL I get this error: 

> Passed value of header "Host" is not allowed. Please contact your license server administrator.

As this service is running behind reverse proxy, I added below environment variable too

JLS_VIRTUAL_HOSTS: mo-jetbrains.qa.XYZ.net,nonprod6-cluster.XYZ.net/license-server-jetbrains

PORT CONFIGURED:

> mapping: 9078:80

**Comment by crazy-max** [comment]
> nonprod6-cluster.XYZ.net/license-server-jetbrains

`nonprod6-cluster.XYZ.net/license-server-jetbrains` is not a valid virtualhost. If you want to change the context you have to use `JLS_CONTEXT` env var.

`JLS_VIRTUAL_HOSTS: mo-jetbrains.qa.XYZ.net,nonprod6-cluster.XYZ.net`

**Comment by kazhian** [comment]
// If you want to change the context you have to use JLS_CONTEXT env var.//

is it possible for you to elaborate, please

**Comment by kazhian** [comment]
@crazy-max I am good now. Created a routing URL which solved the problem
