### ISSUE TITLE
When passing PUID and GUID license server configuration fails 

### ISSUE THREAD

**Issue by RaghvendraGarg** [crazy-max/docker-jetbrains-license-server#44]
### Behaviour
When overriding the user id and group id using environment variables PUID & GUID, the configuration of license server fails and sever starts with standard port 8080 but remains unaccessible.  
#### Steps to reproduce this issue

1. create user with uid 1050 and group id 1050
2. docker run \
     --detach \
     --restart=always \
     -v /opt/jetbrains/data:/data \
     -p 80:8000 \
     -e PUID=1050 \
     -e PGID=1050 \
      crazymax/jetbrains-license-server:25980
3. try to curl 0.0.0.0/register, it will fail.

#### Expected behaviour
 curl 0.0.0.0/register should work with 200 HTTP status 
> Tell me what should happen

#### Actual behaviour
curl 0.0.0.0/register fails with following error "curl: (56) Recv failure: Connection reset by peer"

after updating the entrypoint.sh to print the file permissions after switching the user, I can see that the directories and files are still owned by user with 1000 id, which does not exist after replacing it with PUID passed.

```
### Logs

04f527acb9e0: Switching to PGID 1050...
04f527acb9e0: Switching to PUID 1050...
04f527acb9e0: Setting timezone to UTC...
04f527acb9e0: total 8
**04f527acb9e0: drwxr-xr-x 3    0    0 4096 Jan 30 01:20 java
04f527acb9e0: drwxr-xr-x 7 1000 1000 4096 Feb 18 14:15 jetbrains-license-server**
04f527acb9e0: total 32
**04f527acb9e0: drwxr-xr-x 2 1000 1000 4096 Feb  8 20:36 bin
04f527acb9e0: drwxr-xr-x 2 1000 1000 4096 Feb  8 20:36 conf
04f527acb9e0: drwxr-xr-x 6 1000 1000 4096 Feb  8 20:36 launcher
04f527acb9e0: drwxr-xr-x 2 1000 1000 4096 Feb  8 20:36 lib
04f527acb9e0: -rwxr-xr-x 1 1000 1000  106 Feb  8 20:36 service.build.properties
04f527acb9e0: -rwxr-xr-x 1 1000 1000    4 Feb  8 20:36 service.conf.location
04f527acb9e0: -rwxr-xr-x 1 1000 1000  415 Feb  8 20:36 service.properties
04f527acb9e0: drwxr-xr-x 4 1000 1000 4096 Feb  8 20:36 web**
04f527acb9e0: Initializing files and folders...
04f527acb9e0: Configuring Jetbrains License Server...
04f527acb9e0: **Config directory is not writable: /opt/jetbrains-license-server/conf**
04f527acb9e0: Following virtual hosts will be used:
04f527acb9e0: -> jetbrains-internal-vhost
04f527acb9e0: **Config directory is not writable: /opt/jetbrains-license-server/conf**
04f527acb9e0: Enabling stats via API at /2021-02-18T10:50:36Z...
04f527acb9e0: **Config directory is not writable: /opt/jetbrains-license-server/conf**

**Comment by crazy-max** [comment]
@RaghvendraGarg Should be fixed now.
