### ISSUE TITLE
Unsupported java version is used

### ISSUE THREAD

**Issue by NickWemekamp** [crazy-max/docker-jetbrains-license-server#53]
### Behaviour

The [Jetbrains license server documentation](https://www.jetbrains.com/help/license_server/requirements.html) says that only Java 8 is supported and that Java 9 or later is not supported. This image uses Java 15 so the image version should be changed to version 8. 

Because of the Java version the proxy configuration is also not picked up by the Jetbrains License server. I have installed JLS manually on an adoptopenjdk:8-jre-hotspot and my proxy configuration is working on this image but when I install JLS manually on an adoptopenjdk:15-jre-hotspot image the proxy server configuration is not picked up and JLS can't connect to Jetbrains. The proxy server configuration is also not used when I use this JLS image (even though I can see that the JVM was invoked with the http.proxyHost arguments) so I assume that the proxy server settings are not used because an unsupported Java version for JLS is used in this image.

#### Expected behaviour

> Java 8 is used as a base image. And proxy server configuration is picked up correctly.

#### Actual behaviour

> Java 15 is used. The proxy server is never used and HTTP calls timeout.

**Comment by crazy-max** [comment]
@NickWemekamp Thanks for your feedback. Will fix that asap.
