### ISSUE TITLE
How to use admin account?

### ISSUE THREAD

**Issue by ddoo5** [crazy-max/docker-jetbrains-license-server#73]
I register new account, then up docker container. When i login on 'register server', it wrote: 
'JetBrains License Server
You need admin access to your organization profile for license server registration.'

**Comment by Tapac** [comment]
Please follow the [JetBrains official instruction](https://www.jetbrains.com/help/license-vault-cloud/getting_started.html)

**Comment by KunalScriptz** [comment]
I am also facing same issue, i have been going through the docs, but its not clearly mentioned.
Could u just help me out pls?
How do i get admin access? i have self hosted this license server succesfully
