### ISSUE TITLE
Mount denied

### ISSUE THREAD

**Issue by neomaximus2k** [crazy-max/docker-jetbrains-license-server#8]
When using the image on a windows docker using linux containers I get the below errors

``
PS D:\PhpStormLicenseServer> docker-compose up -d
Creating phpstormlicenseserver_traefik_1 ... error

ERROR: for phpstormlicenseserver_traefik_1  Cannot create container for service traefik: b'Mount denied:\nThe source path "\\\\var\\\\run\\\\docker.sock:/var/run/docker.sock"\nis not a valid Windows path'

ERROR: for traefik  Cannot create container for service traefik: b'Mount denied:\nThe source path "\\\\var\\\\run\\\\docker.sock:/var/run/docker.sock"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.
PS D:\PhpStormLicenseServer>
``

**Comment by crazy-max** [comment]
I do not use Docker with Windows. Take a look at [this comment](https://github.com/docker/for-win/issues/1829#issuecomment-374560724) or [post an issue on traefik repo](https://github.com/containous/traefik/issues).
