### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c apk add --update --no-cache

### ISSUE THREAD

**Issue by esfomeado** [crazy-max/docker-jetbrains-license-server#88]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-jetbrains-license-server/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I ran `docker buildx bake` I get this error:

ERROR: failed to solve: process "/bin/sh -c apk add --update --no-cache     bash     ca-certificates     curl     openjdk11-jre     openssl     shadow     zip     tzdata   && mkdir -p /data \"$JLS_PATH\"   && curl -L \"https://download.jetbrains.com/lcsrv/license-server-installer.zip\" -o \"/tmp/jls.zip\"   && echo \"$JLS_SHA256  /tmp/jls.zip\" | sha256sum -c - | grep OK   && unzip \"/tmp/jls.zip\" -d \"$JLS_PATH\"   && rm -f \"/tmp/jls.zip\"   && chmod a+x \"$JLS_PATH/bin/license-server.sh\"   && ln -sf \"$JLS_PATH/bin/license-server.sh\" \"/usr/local/bin/license-server\"   && addgroup -g ${PGID} jls   && adduser -u ${PUID} -G jls -h /data -s /bin/bash -D jls   && chown -R jls. /data \"$JLS_PATH\"   && rm -rf /tmp/*" did not complete successfully: exit code: 1

### Expected behaviour

Docker build should succeed

### Actual behaviour

Errors instead

### Steps to reproduce

Run `docker buildx bake`

### Docker info

```text
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 7.456GiB
 Name: docker-desktop
 ID: dacc6f31-8370-43ee-8782-ea6ebcce1b29
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Logs

```text
N/A
```

**Comment by penguinvovan** [comment]
Try using a VPN to build docker image. That's works for me.

**Comment by ilyazheprog** [comment]
with VPN dont work

**Comment by crazy-max** [comment]
Could not repro with latest release https://github.com/crazy-max/docker-jetbrains-license-server/releases/tag/39687-r0

> `did not complete successfully: exit code: 1`

I pushed some changes in https://github.com/crazy-max/docker-jetbrains-license-server/pull/96 to make the build a bit more verbose if you can try again.

Closing in the meantime but let me know if you still encounter this issue.
